[package]
name = "rollers"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
dotenvy = "0.15.7"
lazy_static = "1.5.0"
pest = "2.8.0"
pest_derive = "2.8.0"
poise = "0.6.1"
rand = "0.9.1"
thiserror = "2.0.12"
tokio = { version = "1.45.0", features = ["full"] }
